name: Test Next.js Builds

on:
  schedule:
    # Runs everyday at 17:30 UTC
    - cron: '30 17 * * *'

jobs:
  build-check:
    name: Check if Next.js app builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # get all history for the diff
          fetch-depth: 0
      - name: Set up Node (14)
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Get release version
        id: get-version
        run: |
          echo "CANARY_VERSION=$(npm view firebase@canary version)" >> $GITHUB_OUTPUT
      - name: Yarn install canary version of firebase
        run: |
          echo "Installing firebase@canary, version: ${{ steps.get-version.outputs.CANARY_VERSION }}"
          yarn add firebase@canary
          yarn
      - name: Run build for Next.js app
        run: yarn build
      - name: Tests succeeded
        if: success()
        run: node scripts/ci/notify-test-result.js success
        env:
          WEBHOOK_URL: ${{ secrets.JSCORE_CHAT_WEBHOOK_URL }}
          FIREBASE_CANARY_VERSION: ${{ steps.get-version.outputs.CANARY_VERSION }}
      - name: Tests failed
        if: failure()
        run: node scripts/ci/notify-test-result.js fail
        env:
          WEBHOOK_URL: ${{ secrets.JSCORE_CHAT_WEBHOOK_URL }}
          FIREBASE_CANARY_VERSION: ${{ steps.get-version.outputs.CANARY_VERSION }}
