name: Test Next.js Builds

on: pull_request

jobs:
  build-check:
    name: Check if Next.js app builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # get all history for the diff
          fetch-depth: 0
      - name: Set up Node (14)
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Yarn install canary version of firebase
        run: |
          echo "Installing firebase@canary"
          yarn add firebase@canary
          yarn
      - name: Run build for Next.js app
        run: yarn build
